 version: "3"
 services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      - PORT=3000
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - SESSION_SECRET=testingsecret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password